"""deepspeechlog  table

Revision ID: 195a0692fa5e
Revises: d1576c615fe8
Create Date: 2021-05-27 12:42:50.640426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195a0692fa5e'
down_revision = 'd1576c615fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deep_speech_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deep_speech_log_timestamp'), 'deep_speech_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deep_speech_log_timestamp'), table_name='deep_speech_log')
    op.drop_table('deep_speech_log')
    # ### end Alembic commands ###
