"""new fields in deepspeechlog  model

Revision ID: c2f3ed4df090
Revises: ce516a4943c9
Create Date: 2021-05-29 14:34:04.213399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f3ed4df090'
down_revision = 'ce516a4943c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deep_speech_log', sa.Column('question', sa.String(length=140), nullable=True))
    op.add_column('deep_speech_log', sa.Column('answer', sa.String(length=140), nullable=True))
    op.drop_column('deep_speech_log', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deep_speech_log', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('deep_speech_log', 'answer')
    op.drop_column('deep_speech_log', 'question')
    # ### end Alembic commands ###
